import type * as THREE from "three";

/**
 * Augment this interface in your project's `prefabs.d.ts` (auto-generated by
 * the react-three-engine Vite plugin) to get typed `ref` callbacks on
 * `<Prefab id="..." ref={...} />`.
 *
 * Each key is a prefab file stem (e.g. `"test-prefab"`).
 * Each value is a `THREE.Group` subtype whose `children` tuple reflects the
 * root-level objects saved in the prefab file.
 *
 * @example
 * // auto-generated prefabs/prefabs.d.ts
 * declare module "react-three-engine" {
 *   interface PrefabTypeRegistry {
 *     "test-prefab": import("three").Group & { children: [import("three").Mesh] };
 *   }
 * }
 */
// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface PrefabTypeRegistry {}

/** Resolves the ref type for a given prefab id. Falls back to `THREE.Group`. */
export type PrefabRef<K extends string> = K extends keyof PrefabTypeRegistry
  ? PrefabTypeRegistry[K]
  : THREE.Group;
